### ISSUE TITLE
[WordPress Scoutnet Kalender] Fix für deprecated construct

### ISSUE THREAD

**Issue by ManniLoe** [scoutnet/public#41]
PHP Notice:  Die verwendete Konstruktoren-Methode für WP_Widget ist seit Version 4.3.0 <strong>veraltet</strong>! Verwende stattdessen `__construct()`.

Im gist ist ein Patch für die aktuelle WordPress Version.
https://gist.github.com/ManniLoe/24afca6a10b6da3af2f2

Btw, es wäre aus gut (sinnvoll) das Plugin hier in github mit zu hinterlegen, habe da ein paar "pull requests"

Gruß
Manni

**Comment by peduso** [comment]
Hallo Manni,

ich geb das mal weiter. Bin mir nicht so sicher worum es geht, aber 
Mütze und die Kollegen kennen sich sicher aus.


Viele Grüße,
Peter


Am 26.11.2015 um 15:16 schrieb Manfred Löbling:

**Comment by sHorst** [comment]
hey manni,

das wordpress plugin liegt im wordpress svn .. und wird nicht von uns sondern von Björn (roverreferent aus dem dv Paderborn) verwaltet. Ich hab da zwar schreib rechte, aber federführend macht Björn das. am besten da mal die pull Requests rein packen..

https://wordpress.org/plugins/scoutnet-kalender/

Mit freundlichen Grüßen

Mütze
