### ISSUE TITLE
[WordPress Scoutnet Kalender] Zeitverschiebung bei Uhrzeiten

### ISSUE THREAD

**Issue by sbaschtl** [scoutnet/public#42]
Die Anfangs- bzw. Endzeiten der einzelnen Termine sind um eine Stunde nach vorne verschoben.

Beispiele:

- http://www.bezirk-breisgau.de/termine/ → http://kalender.scoutnet.de/2.0/show.php?id=376

- http://www.dpsg-paderborn.de → http://kalender.scoutnet.de/2.0/show.php?id=53

- http://dpsg-passau.de/aktionen/termine/ → http://kalender.scoutnet.de/2.0/show.php?id=310

**Comment by cvogt** [comment]
danke @sbaschtl wir werden uns der Sache umgehend annehmen

**Comment by sbaschtl** [comment]
Vielen Dank, @cvogt!

**Comment by sHorst** [comment]
Hey,

ich hab das problem behoben.. war mal wieder UTC und Zeitzonen Probleme .. die API gibt alle Daten im UTC format aus.

Also jetzt wieder..

Mütze

**Comment by sbaschtl** [comment]
@sHorst Dankeschön!
