### ISSUE TITLE
[Kalender] Hinweis nach Bearbeitung eines Termins

### ISSUE THREAD

**Issue by ManniLoe** [scoutnet/public#43]
Hi,

es ist sehr verwirrend das man nach dem Bearbeiten eines Termins (erfolgreich!) die Nachricht
als "alert-danger" angezeigt bekommt...
Ein "alert-success" / "alert-info" wäre da wohl angebrachter.

```
<div class="typo3-messages">
<div class="typo3-message message-error alert alert-danger">
<div class="message-body">Termin gespeichert</div></div></div>
```

![image](https://cloud.githubusercontent.com/assets/1992033/14910077/8d8aa990-0dea-11e6-8f50-41b2957886f0.png)

**Comment by ManniLoe** [comment]
![image](https://cloud.githubusercontent.com/assets/1992033/14910155/51b005cc-0deb-11e6-8c84-aec61225436f.png)

**Comment by sHorst** [comment]
hey .. auch wenn das nur eye candy ist .. ich hab es gefixt :) wenn alle bugs soo einfach währen .. :)

sieht man sich bei der webcon? https://barcamptools.eu/webmaster-convention-2016

**Comment by ManniLoe** [comment]
Danke, ja ist ja nur eine Kleinigkeit :)
Webcon steht zumindest schon im Kalender, zu 95% bin ich dabei!
