### ISSUE TITLE
Enforced HTTPS-Umleitung für http://kalender.scoutnet.de/2.0/ blockiert externe Templates

### ISSUE THREAD

**Issue by eFloh** [scoutnet/public#47]
Repro-URL: http://kalender.scoutnet.de/2.0/show.php?id=328&template=http%3A%2F%2Fwww%2Edpsg-stamm-falke%2Ede%2Fkalender%2Etpl&ebenenup=0

Die URL leitet auf die https-Variante von kalender.scoutnet.de weiter. DasTemplate wird noch korrekt eingebunden, aktuelle Browser verhindern dann allerdings die darin enthaltenen Resourcen wie z.B. externe CSS-Dateien, da die unsicheren Verbindungen aus der sicheren Seite aus nicht erlaubt sind.

--> Kalenderdarstellung defekt.

Nicht jede Homepage/gehoste Template-Datei kann ohne weiteres auf https-Links umgestellt werden, daher wäre eine optionale https-Variante bevorzugt.

Für mich: Für viele Browser lösbar durch Aktivierung eines lets-encrypt-Zertifikats dank meinem Hoster. Diese sind aber noch nicht flächendeckend in den Browsern vertrauenswürdig.

**Comment by sHorst** [comment]
für diese faelle tut die scoutnet seite auch nicht :) is auch lets encrypt. wir setzen hsts header mit langer laufzeit, plus preload, was uns verpflichtet auto update auf https zu machen. und aus sicherheitsgründen macht es auch keinen sinn https nicht zu enforcen .. mit lets encrypt gibt es fuer keinen hoster mehr eine ausrede https nicht einzusetzen .. alternativ kann man immer home.scoutnet.de zu nutzen .. also bug abgelehnt .. das is so gewollt.

**Comment by eFloh** [comment]
So gerne akzeptiert von mir, nun auch für andere dokumentiert.

Wäre nur prima gewesen, die bevorstehende Umstellung zu erfahren, bevor Besucher sich über unsere Seite melden, dass die kaputt ist...

**Comment by janbrohl** [comment]
Über eine der APIs die Daten zu ziehen und Selbst in ein template zu füllen ist meiner Meinung nach die günstigere Lösung

**Comment by cvogt** [comment]
@janbrohl Ist es. Die template Lösung ist von 2002, aus einer Zeit bevor webservices cool und mainstream waren. Und sie hat uns erlaubt Beispiele online zu stellen die jeder benutzen und anpassen konnte, selbst mit nur HTML Kenntnissen. Aber wenn wir Leute migrieren können, great.

**Comment by peduso** [comment]
@eFloh Du hast recht, dass wir in der Kommunikation oft zu schwach sind. Leider sind wir so knapp an Stunden, dass uns das vielleicht mal durchgeht. We try to get better...
