### ISSUE TITLE
Bechreibung bei CalDAV

### ISSUE THREAD

**Issue by janbrohl** [scoutnet/public#48]
Wenn ich mir den Kalender über https://webcal.scoutnet.de/webcal/ hole dann bestehen für mich die Beschreibungen der Termine aus einem JSON-Objekt (das nur unter anderem die Beschreibung enthält)

Thunderbird 46.7.1 mit Lightning 4.7.7.1

**Comment by sHorst** [comment]
ja. das soll so. und ist is jedem browser/caldav client so :)

da Caldav keine Felder für zB stufe, Kategorie etc hat, musste ich ein Feld zweckentfremden. Dies ist das Beschreibungs feld geworden. Wenn du in das json Inhalt einträgst, so landet dieser auch wieder im Kalender. Und man kann so Kategorien verwenden.

**Comment by janbrohl** [comment]
Tatsächlich gibt es:
-  ein optionales Feld für Kategorien namens categories -> https://tools.ietf.org/html/rfc5545#section-3.8.1.2
- ein optionales Feld für Veranstalter namens organizer -> https://tools.ietf.org/html/rfc5545#section-3.8.4.3

Für Link_Text habe ich zwar keine Entsprechung gefunden aber zumindest in unserem Kalender habe ich noch keine Benutzung dieses Feldes gesehen.

**Comment by sHorst** [comment]
link text wird bei manschen Kalendern genutzt.. und die beiden Felder werden nicht auf dem iphone/mac genutzt, weshalb sie raus fallen.
